### PR TITLE
Fe lists products#5

### PR DESCRIPTION
**Pull request by MillanAir**
Added Dialogs for creating a list and add a product

### CODE REVIEW

**Comment by jason1794c** [comment]
In ListsContainer, UserDashboard, AddItem, AddNewList, and ListCards, props is a parameter for each of the components. However, I don't see any of the components having props, so I don't think having props as a parameter is necessary here. Otherwise, the code looks fine to me. The dashboard looks great!

**Comment by MillanAir** [comment]
Thanks, Jason
Removed unused props on ListsContainer, UserDashboard, AddItem, AddNewList, and ListCards.

**Comment by MillanAir** [comment]
Resolved console warnings

**Review by jessdesr — APPROVED** [review]

**Review by shenziq1 — APPROVED** [review]
Remove .env and add it to .gitignore.
This is what I should have done last time.
This information should only be stored locally in development, not published on github.

**Comment by MillanAir** [comment]
Resolved conflicts and merged

**Pull request merged**
